---
- name: Install packets to master node
  hosts: master
  become: yes
  tasks:
    - name: Update and upgrade packets
      apt:
        upgrade: yes
        update_cache: yes
        cache_valid_time: 86400
    - name: Install required system packages
      apt: 
        pkg:
          - curl
          - gnupg2
          - software-properties-common
          - apt-transport-https
          - ca-certificates
        state: latest
        update_cache: yes

        
    - name: Add Docker GPG apt Key
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present
      #shell: curl -fsSL https://download.docker.com/linux/ubuntu/gpg | gpg --dearmour -o /etc/apt/trusted.gpg.d/docker.gpg

    - name: Add Docker Repository
      apt_repository:
        repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable
        state: present

    
    # - name: Get Kubernetes packege key
    #   apt_key:
    #     url: https://pkgs.k8s.io/core:/stable:/v1.30/deb/Release.key
    #     state: present
    #         # - name: Get Kubernetes packege key
    #   #shell: curl -fsSL https://pkgs.k8s.io/core:/stable:/v1.30/deb/Release.key |  gpg --dearmor -o /etc/apt/keyrings/kubernetes-apt-keyring.gpg
    
    # - name: Add Kubernetes repository
    #   apt_repository:
    #     repo: "deb [signed-by=/etc/apt/keyrings/kubernetes-apt-keyring.gpg] https://pkgs.k8s.io/core:/stable:/v1.30/deb/ /"
    #     filename: kubernetes
    